#!/bin/bash

rm -rf autom4te.cache
rm -f aclocal.m4
rm -f compile
rm -f config.h
rm -f config.h.in
rm -f config.log
rm -f config.status
rm -f configure
rm -f depcomp
rm -f install-sh
rm -f Makefile
rm -f Makefile.in
rm -f missing
rm -f stamp-h1
rm -rf src/.deps
rm -f src/Makefile
rm -f src/Makefile.in
rm -f cogaps
autoreconf -i
mkdir -p build
cd build
../configure
make
./cogaps --help
cd ..
